"""Cryptography test vectors for Nuki protocol."""

# Test vectors for NaCl encryption/decryption
# These are deterministic test values for unit testing

# Bridge keypair (test values)
BRIDGE_PUBLIC_KEY = bytes.fromhex(
    "8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a"
)
BRIDGE_PRIVATE_KEY = bytes.fromhex(
    "5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb"
)

# Nuki device keypair (test values)
NUKI_PUBLIC_KEY = bytes.fromhex(
    "de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f"
)
NUKI_PRIVATE_KEY = bytes.fromhex(
    "4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742"
)

# Shared secret (computed from the two keypairs)
SHARED_SECRET = bytes.fromhex(
    "6a6f724ceb4df416cf6db24fb6c8e89fb21e51c6c85dcfeb" + "142e1b5cdb38805a"
)

# Auth ID
TEST_AUTH_ID = 123456  # 0x0001E240

# Test nonce (24 bytes for NaCl)
TEST_NONCE = bytes.fromhex(
    "000000000000000000000000000000000000000000000000"
)

# Test plaintext command
TEST_PLAINTEXT_LOCK_ACTION = bytes.fromhex(
    "0D"  # Command: LOCK_ACTION
    + "01"  # Action: UNLOCK
    + "0001E240"  # App ID
    + "00"  # Flags
    + "4E616D65"  # Name: "Name"
    + "00" * 20  # Nonce
)

# Expected ciphertext for the plaintext above (using test keys and nonce)
# Note: This would need to be generated by actually encrypting with NaCl
# For testing purposes, we'll use a placeholder
TEST_CIPHERTEXT_LOCK_ACTION = bytes.fromhex(
    "abcd" * 32  # Mock encrypted data (64 bytes)
)

# Token validation test data
TEST_TOKEN = "a1b2c3d4e5f6" * 10 + "a1b2"  # 64-char hex string

# Timestamp for token validation
TEST_TIMESTAMP = "2024-01-15T10:30:00Z"

# Hash token test (hash mode)
# Format: <ts>,<hash>
# hash = SHA256(ts + "," + token)
TEST_HASH_TOKEN_TS = "1234567890"
TEST_HASH_TOKEN_HASH = "5f4dcc3b5aa765d61d8327deb882cf99"  # Mock hash
TEST_HASH_TOKEN = f"{TEST_HASH_TOKEN_TS},{TEST_HASH_TOKEN_HASH}"

# CToken test (ctoken mode)
# Format: <ts>,<hash>
# hash = SHA256(action + "," + nukiId + "," + ts + "," + token)
TEST_CTOKEN_ACTION = "lock"
TEST_CTOKEN_NUKI_ID = "12345678"
TEST_CTOKEN_TS = "1234567890"
TEST_CTOKEN_HASH = "7c6a180b36896a0a8c02787eeafb0e4c"  # Mock hash
TEST_CTOKEN = f"{TEST_CTOKEN_TS},{TEST_CTOKEN_HASH}"

# HMAC test vectors
TEST_HMAC_KEY = bytes.fromhex("aa" * 32)
TEST_HMAC_MESSAGE = b"Test message for HMAC"
TEST_HMAC_DIGEST = bytes.fromhex(
    "1234567890abcdef" * 4  # Mock HMAC-SHA256 output (32 bytes)
)
